name: Auto-build and publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libsfml-dev libluajit-5.1-dev liblua5.3-0
        
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - uses: actions/setup-python@v1
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: build
          
      - name: Compress build
        run: tar -cvzf p2dlinux.tar.gz build/assets build/P2D README.md LICENSE
        
      - name: Remove previous auto-release
        uses: cb80/delrel@latest
        with:
          tag: autorelease
          token: ${{ secrets.GITHUB_TOKEN }}

        
      - name: Create new auto-release
        uses: softprops/action-gh-release@v1
        with:
          body: "Warning, this release is automatically built from the git repository every time something is pushed, expect bugs and glitches beyond your wildest nightmares..."
          tag_name: autorelease
          files: p2dlinux.tar.gz
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
