name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get install libsfml-dev libluajit-5.1-dev
        
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - uses: actions/setup-python@v1
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: build
          
      - name: Compress build
        run: tar -cvzf p2dlinux.tar.gz build/assets build/P2D README.md LICENSE
        
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: p2d-git-autorelease
          files: p2dlinux.tar.gz
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
