name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get install libsfml-dev libluajit-5.1-dev
        
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - uses: actions/setup-python@v1
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: build
